// namespace DYH.Tools;
// #if NET35
// public static class NET35Tool
// {
//     public static System.Drawing.Point GetLocation(this Window window) => window.Location;
//     public static object GetAcadDocument(this Document doc) => doc.AcadDocument;
//     public static RibbonControl GetRibbonControl()
//     {
//         return Autodesk.AutoCAD.Ribbon.RibbonServices.RibbonPaletteSet.RibbonControl;
//     }
// }
// #endif
// #if zcad
// public static class ZWCadTool
// {
//     public static System.Drawing.Point GetLocation(this Window window)=>window.Location;
//     public static object GetAcadDocument(this Document doc)=>doc.ZcadDocument;
// }
// #endif