<?xml version="1.0"?>
<doc>
    <assembly>
        <name>DotNetARX</name>
    </assembly>
    <members>
        <member name="M:DotNetARX.Tools.AddToModelSpace(Autodesk.AutoCAD.DatabaseServices.Database,Autodesk.AutoCAD.DatabaseServices.Entity)">
            <summary>
            将实体添加到模型空间
            </summary>
            <param name="db">数据库对象</param>
            <param name="ent">要添加的实体</param>
            <returns>返回添加到模型空间中的实体ObjectId</returns>
        </member>
        <member name="M:DotNetARX.Tools.AddToModelSpace(Autodesk.AutoCAD.DatabaseServices.Database,Autodesk.AutoCAD.DatabaseServices.Entity[])">
            <summary>
            将实体添加到模型空间
            </summary>
            <param name="db">数据库对象</param>
            <param name="ents">要添加的多个实体</param>
            <returns>返回添加到模型空间中的实体ObjectId集合</returns>
        </member>
        <member name="M:DotNetARX.Tools.HandleToObjectId(Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            将字符串形式的句柄转化为ObjectId
            </summary>
            <param name="db">数据库对象</param>
            <param name="handleString">句柄字符串</param>
            <returns>返回实体的ObjectId</returns>
        </member>
        <member name="T:DotNetARX.LineTypeTools">
            <summary>
            线型操作类
            </summary>
        </member>
        <member name="M:DotNetARX.LineTypeTools.AddLineType(Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            创建一个新的线型
            </summary>
            <param name="db">数据库对象</param>
            <param name="typeName">线型名</param>
            <returns>返回新建线型的Id</returns>
        </member>
        <member name="M:DotNetARX.LineTypeTools.LoadLineType(Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            从“acadiso.lin”线型文件中装载指定线型
            </summary>
            <param name="db">数据库对象</param>
            <param name="typeName">线型名</param>
            <returns>返回装载的线型的Id</returns>
        </member>
        <member name="T:DotNetARX.LineTypeTools.Shape">
            <summary>
            用于形定义文件的图案
            </summary>
        </member>
        <member name="F:DotNetARX.LineTypeTools.Shape.Track">
            <summary>
            竖线
            </summary>
        </member>
        <member name="F:DotNetARX.LineTypeTools.Shape.Zig">
            <summary>
            Z字型
            </summary>
        </member>
        <member name="F:DotNetARX.LineTypeTools.Shape.Box">
            <summary>
            矩形
            </summary>
        </member>
        <member name="F:DotNetARX.LineTypeTools.Shape.Circle">
            <summary>
            圆
            </summary>
        </member>
        <member name="F:DotNetARX.LineTypeTools.Shape.Bat">
            <summary>
            S型
            </summary>
        </member>
        <member name="M:DotNetARX.GeTools.RadianToDegree(System.Double)">
            <summary>
            将弧度值转换为角度值
            </summary>
            <param name="angle">弧度</param>
            <returns>返回角度值</returns>
        </member>
        <member name="M:DotNetARX.GeTools.DegreeToRadian(System.Double)">
            <summary>
            将角度值转换为弧度值
            </summary>
            <param name="angle">角度</param>
            <returns>返回弧度值</returns>
        </member>
        <member name="M:DotNetARX.GeTools.PolarPoint(Autodesk.AutoCAD.Geometry.Point3d,System.Double,System.Double)">
            <summary>
            获取与给定点指定角度和距离的点
            </summary>
            <param name="point">给定点</param>
            <param name="angle">角度</param>
            <param name="dist">距离</param>
            <returns>返回与给定点指定角度和距离的点</returns>
        </member>
        <member name="M:DotNetARX.GeTools.MidPoint(Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
            <summary>
            获取两个点之间的中点
            </summary>
            <param name="pt1">第一点</param>
            <param name="pt2">第二点</param>
            <returns>返回两个点之间的中点</returns>
        </member>
        <member name="M:DotNetARX.GeTools.AngleFromXAxis(Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
            <summary>
            计算从第一点到第二点所确定的矢量与X轴正方向的夹角
            </summary>
            <param name="pt1">第一点</param>
            <param name="pt2">第二点</param>
            <returns>返回两点所确定的矢量与X轴正方向的夹角</returns>
        </member>
        <member name="T:DotNetARX.CircleTools">
            <summary>
            简化圆操作类
            </summary>
        </member>
        <member name="M:DotNetARX.CircleTools.CreateCircle(Autodesk.AutoCAD.DatabaseServices.Circle,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
            <summary>
            两点创建圆
            </summary>
            <param name="circle">圆对象</param>
            <param name="startPoint">起点</param>
            <param name="endPoint">终点</param>
        </member>
        <member name="M:DotNetARX.CircleTools.CreateCircle(Autodesk.AutoCAD.DatabaseServices.Circle,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
            <summary>
            三点法创建圆
            </summary>
            <param name="circle">圆对象</param>
            <param name="pt1">第一点</param>
            <param name="pt2">第二点</param>
            <param name="pt3">第三点</param>
            <returns>若成功创建圆，则返回true，否则返回false</returns>
        </member>
        <member name="T:DotNetARX.SummaryInfoTools">
            <summary>
            摘要信息操作类
            </summary>
        </member>
        <member name="M:DotNetARX.SummaryInfoTools.NumCustomProperties(Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            获取摘要信息中的自定义属性个数
            </summary>
            <param name="db">数据库对象</param>
            <returns>返回自定义属性个数</returns>
        </member>
        <member name="M:DotNetARX.SummaryInfoTools.HasCustomProperty(Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            判断图形中是否存在指定的自定义属性
            </summary>
            <param name="db">数据库对象</param>
            <param name="key">自定义属性的名称</param>
            <returns>如果存在指定的自定义属性，返回true，否则返回false</returns>
        </member>
        <member name="M:DotNetARX.SummaryInfoTools.HasSummaryInfo(Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            判断图形中是否存在摘要信息
            </summary>
            <param name="db">数据库对象</param>
            <returns>如果存在摘要信息，返回true，否则返回false</returns>
        </member>
        <member name="M:DotNetARX.SummaryInfoTools.CreationTime(Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            获取图形创建的时间
            </summary>
            <param name="db">数据库对象</param>
            <returns>返回图形创建的时间</returns>
        </member>
        <member name="M:DotNetARX.SummaryInfoTools.ModifyTime(Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            获取图形的上次修改时间
            </summary>
            <param name="db">数据库对象</param>
            <returns>返回图形的上次修改时间</returns>
        </member>
        <member name="M:DotNetARX.SummaryInfoTools.TotalEditTime(Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            获取编辑图形的总时间
            </summary>
            <param name="db">数据库对象</param>
            <returns>返回编辑图形的总时间</returns>
        </member>
        <member name="M:DotNetARX.SummaryInfoTools.ConvertAcadJulianToDateTime(System.Double)">
            <summary>
            将儒略日时间格式转换为DateTime格式
            </summary>
            <param name="julianDate">儒略日时间</param>
            <returns>返回DateTime格式的时间</returns>
        </member>
        <member name="T:DotNetARX.AnnotateTools">
            <summary>
            注释缩放操作类
            </summary>
        </member>
        <member name="M:DotNetARX.AnnotateTools.AddScale(Autodesk.AutoCAD.DatabaseServices.Database,System.String,System.Double,System.Double)">
            <summary>
            为图形添加一个新的注释比例
            </summary>
            <param name="db">图形数据库对象</param>
            <param name="scaleName">缩放比例名</param>
            <param name="paperUnits">缩放比例的图纸单位</param>
            <param name="drawingUnits">缩放比例的图形单位</param>
            <returns>返回添加的注释比例</returns>
        </member>
        <member name="M:DotNetARX.AnnotateTools.AttachScale(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String[])">
            <summary>
            为实体添加指定的注释比例
            </summary>
            <param name="entId">实体的Id</param>
            <param name="scaleNames">注释比例名列表</param>
        </member>
        <member name="M:DotNetARX.AnnotateTools.GetAllScales(Autodesk.AutoCAD.DatabaseServices.ObjectId)">
            <summary>
            获取实体拥有的所有缩放比例
            </summary>
            <param name="entId">实体的Id</param>
            <returns>返回实体的缩放比例列表</returns>
        </member>
        <member name="M:DotNetARX.AnnotateTools.RemoveScale(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String[])">
            <summary>
            删除实体的缩放比例
            </summary>
            <param name="entId">实体的Id</param>
            <param name="scaleNames">缩放比例名列表</param>
        </member>
        <member name="T:DotNetARX.FontCharSet">
            <summary>
            字体字符集名称
            </summary>
        </member>
        <member name="F:DotNetARX.FontCharSet.Ansi">
            <summary>
            英文
            </summary>
        </member>
        <member name="F:DotNetARX.FontCharSet.Default">
            <summary>
            与当前操作系统语言有关，如为简体中文，则被设置为GB2312
            </summary>
        </member>
        <member name="F:DotNetARX.FontCharSet.GB2312">
            <summary>
            简体中文
            </summary>
        </member>
        <member name="F:DotNetARX.FontCharSet.Big5">
            <summary>
            繁体中文
            </summary>
        </member>
        <member name="F:DotNetARX.FontCharSet.OEM">
            <summary>
            与操作系统有关
            </summary>
        </member>
        <member name="T:DotNetARX.FontPitch">
            <summary>
            字体的字宽
            </summary>
        </member>
        <member name="F:DotNetARX.FontPitch.Default">
            <summary>
            默认字宽
            </summary>
        </member>
        <member name="F:DotNetARX.FontPitch.Fixed">
            <summary>
            固定字宽
            </summary>
        </member>
        <member name="F:DotNetARX.FontPitch.Variable">
            <summary>
            可变字宽
            </summary>
        </member>
        <member name="T:DotNetARX.FontFamily">
            <summary>
            字体的语系定义
            </summary>
        </member>
        <member name="F:DotNetARX.FontFamily.Dontcare">
            <summary>
            使用默认字体
            </summary>
        </member>
        <member name="F:DotNetARX.FontFamily.Roman">
            <summary>
            可变的笔划宽度，有衬线，如MS Serif字体
            </summary>
        </member>
        <member name="F:DotNetARX.FontFamily.Swiss">
            <summary>
            可变的笔划宽度，无衬线，如MS Sans Serif字体 
            </summary>
        </member>
        <member name="F:DotNetARX.FontFamily.Modern">
            <summary>
            固定笔划宽度，衬线可以有也可以没有,如Courier New字体
            </summary>
        </member>
        <member name="F:DotNetARX.FontFamily.Script">
            <summary>
            手写体，如Cursive字体
            </summary>
        </member>
        <member name="F:DotNetARX.FontFamily.Decorative">
            <summary>
            小说字体，如旧式英语
            </summary>
        </member>
        <member name="T:DotNetARX.TextStyleTools">
            <summary>
            文字样式操作类
            </summary>
        </member>
        <member name="M:DotNetARX.TextStyleTools.AddTextStyle(Autodesk.AutoCAD.DatabaseServices.Database,System.String,System.String,System.String)">
            <summary>
            创建一个新的文字样式
            </summary>
            <param name="db">数据库对象</param>
            <param name="styleName">文字样式名</param>
            <param name="fontFilename">字体文件名</param>
            <param name="bigFontFilename">大字体文件名</param>
            <returns>返回添加的文字样式的Id</returns>
        </member>
        <member name="M:DotNetARX.TextStyleTools.AddTextStyle(Autodesk.AutoCAD.DatabaseServices.Database,System.String,System.String)">
            <summary>
            创建一个新的文字样式
            </summary>
            <param name="db">数据库对象</param>
            <param name="styleName">文字样式名</param>
            <param name="fontFilename">字体文件名</param>
            <returns>返回添加的文字样式的Id</returns>
        </member>
        <member name="M:DotNetARX.TextStyleTools.AddTextStyle(Autodesk.AutoCAD.DatabaseServices.Database,System.String,System.String,System.Boolean,System.Boolean,System.Int32,System.Int32)">
            <summary>
            创建一个新的文字样式
            </summary>
            <param name="db">数据库对象</param>
            <param name="styleName">文字样式名</param>
            <param name="fontName">字体文件名</param>
            <param name="bold">是否加粗</param>
            <param name="italic">是否倾斜</param>
            <param name="charset">字体的字符集</param>
            <param name="pitchAndFamily">字体的字宽和语系定义</param>
            <returns>返回添加的文字样式的Id</returns>
        </member>
        <member name="M:DotNetARX.TextStyleTools.AddShapeTextStyle(Autodesk.AutoCAD.DatabaseServices.Database,System.String,System.String)">
            <summary>
            添加包含图案的形定义文件
            </summary>
            <param name="db">数据库对象</param>
            <param name="styleName">样式名</param>
            <param name="shapeFilename">形定义文件名</param>
            <returns>返回新添加的文字样式表记录的ObjectId</returns>
        </member>
        <member name="M:DotNetARX.TextStyleTools.SetTextStyleProp(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.Double,System.Double,System.Double,System.Boolean,System.Boolean,System.Boolean,Autodesk.AutoCAD.DatabaseServices.AnnotativeStates,System.Boolean)">
            <summary>
            设置文字样式的有关属性
            </summary>
            <param name="styleId">文字样式的Id</param>
            <param name="textSize">高度</param>
            <param name="xscale">宽度因子</param>
            <param name="obliquingAngle">倾斜角度</param>
            <param name="isVertical">是否垂直</param>
            <param name="upsideDown">是否上下颠倒</param>
            <param name="backwards">是否反向</param>
            <param name="annotative">是否具有注释性</param>
            <param name="paperOrientation">文字方向与布局是否匹配</param>
        </member>
        <member name="T:DotNetARX.PlotSettingsEx">
            <summary>
            增强型打印设置类，支持数据绑定
            </summary>
        </member>
        <member name="M:DotNetARX.PlotSettingsEx.NotifyPropertyChanged(System.String)">
            <summary>
            处理属性更改事件的函数
            </summary>
            <param name="info">属性名</param>
        </member>
        <member name="M:DotNetARX.PlotSettingsEx.#ctor(Autodesk.AutoCAD.DatabaseServices.PlotSettings)">
            <summary>
            复制构造函数，从已有打印设置中获取打印设置
            </summary>
            <param name="ps">已有打印设置</param>
        </member>
        <member name="M:DotNetARX.PlotSettingsEx.UpdatePlotSettings(Autodesk.AutoCAD.DatabaseServices.ObjectId)">
            <summary>
            更新其它的打印设置
            </summary>
            <param name="psId">打印设置对象</param>
        </member>
        <member name="E:DotNetARX.PlotSettingsEx.PropertyChanged">
            <summary>
            在更改属性值时发生的事件
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.CanonicalMediaName">
            <summary>
            获取或设置当前图纸尺寸（中文表示）
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.CurrentStyleSheet">
            <summary>
            获取或设置当前打印样式表
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.CustomPrintScale">
            <summary>
            获取或设置自定义打印比例
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotCentered">
            <summary>
            获取或设置是否居中打印
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotConfigurationName">
            <summary>
            获取或设置当前打印设备名称
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotOrigin">
            <summary>
            获取或设置当前打印原点（原点是从图纸边界的介质边缘偏移而来的）。
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotPaperUnits">
            <summary>
            获取或设置打印比例
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotRotation">
            <summary>
            获取或设置图形方向
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotType">
            <summary>
            获取或设置打印范围
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotViewName">
            <summary>
            获取或设置打印视口名
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotWindowArea">
            <summary>
            获取或设置打印窗口的范围
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.StdScale">
            <summary>
            获取或设置当前标准比例（实数形式）
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.StdScaleType">
            <summary>
            获取或设置当前标准比例（枚举形式）
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.UseStandardScale">
            <summary>
            获取或设置是否选用标准比例
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.Denominator">
            <summary>
            获取或设置当前图形单位
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.Numerator">
            <summary>
            获取或设置当前图纸单位
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotOriginX">
            <summary>
            获取或设置当前X方向的打印偏移
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotOriginY">
            <summary>
            获取或设置当前Y方向的打印偏移
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotExtent">
            <summary>
            获取或设置打印时是否布满图纸
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotReverse">
            <summary>
            获取或设置是否反向打印
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.DeviceList">
            <summary>
            获取当前打印设备列表
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.MediaList">
            <summary>
            获取当前图纸尺寸列表（中文表示）
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotTypeList">
            <summary>
            获取当前打印范围列表（中文表示）
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotUnitList">
            <summary>
            获取当前打印单位列表（中文表示）
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.ColorDependentPlotStyles">
            <summary>
            获取颜色相关打印样式列表
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.NamedPlotStyles">
            <summary>
            获取命名打印样式列表
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.StdScaleTypeList">
            <summary>
            获取标准打印比例列表
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotTypeLocal">
            <summary>
            获取或设置打印范围（中文）
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotPaperUnitsLocal">
            <summary>
            获取或设置打印单位（中文）
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.StdScaleTypeLocal">
            <summary>
            获取或设置当前标准打印比例（中文）
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.IsPlotToFile">
            <summary>
            是否打印到文件
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.NoPlotToFile">
            <summary>
            可以不打印到文件
            </summary>
        </member>
        <member name="P:DotNetARX.PlotSettingsEx.PlotHorizontal">
            <summary>
            获取或设置是否横向打印
            </summary>
        </member>
        <member name="T:DotNetARX.CUITools">
            <summary>
            操作CUI的类
            </summary>
        </member>
        <member name="M:DotNetARX.CUITools.GetMainCustomizationSection(Autodesk.AutoCAD.ApplicationServices.Document)">
            <summary>
            获取并打开主CUI文件
            </summary>
            <param name="doc">AutoCAD文档对象</param>
            <returns>返回主CUI文件</returns>
        </member>
        <member name="M:DotNetARX.CUITools.AddCui(Autodesk.AutoCAD.ApplicationServices.Document,System.String,System.String)">
            <summary>
            创建局部CUI文件
            </summary>
            <param name="doc">AutoCAD文档对象</param>
            <param name="cuiFile">CUI文件名</param>
            <param name="menuGroupName">菜单组的名称</param>
            <returns>返回创建的CUI文件</returns>
        </member>
        <member name="M:DotNetARX.CUITools.LoadCui(Autodesk.AutoCAD.Customization.CustomizationSection)">
            <summary>
            装载指定的局部CUI文件
            </summary>
            <param name="cs">CUI文件</param>
        </member>
        <member name="M:DotNetARX.CUITools.AddMacro(Autodesk.AutoCAD.Customization.CustomizationSection,System.String,System.String,System.String,System.String,System.String)">
            <summary>
            添加菜单项所要执行的宏
            </summary>
            <param name="source">CUI文件</param>
            <param name="name">宏的显示名称</param>
            <param name="command">宏的具体命令</param>
            <param name="tag">宏的标识符</param>
            <param name="helpString">宏的状态栏提示信息</param>
            <param name="imagePath">宏的图标</param>
            <returns>返回创建的宏</returns>
        </member>
        <member name="M:DotNetARX.CUITools.AddPopMenu(Autodesk.AutoCAD.Customization.MenuGroup,System.String,System.Collections.Specialized.StringCollection,System.String)">
            <summary>
            添加下拉菜单
            </summary>
            <param name="menuGroup">包含菜单的菜单组</param>
            <param name="name">菜单名</param>
            <param name="aliasList">菜单的别名</param>
            <param name="tag">菜单的标识字符串</param>
            <returns>返回下拉菜单对象</returns>
        </member>
        <member name="M:DotNetARX.CUITools.AddMenuItem(Autodesk.AutoCAD.Customization.PopMenu,System.Int32,System.String,System.String)">
            <summary>
            为菜单添加菜单项
            </summary>
            <param name="parentMenu">菜单项所属的菜单</param>
            <param name="index">菜单项的位置</param>
            <param name="name">菜单项的显示名称</param>
            <param name="macroId">菜单项的命令宏的Id</param>
            <returns>返回添加的菜单项</returns>
        </member>
        <member name="M:DotNetARX.CUITools.AddSubMenu(Autodesk.AutoCAD.Customization.PopMenu,System.Int32,System.String,System.String)">
            <summary>
            为下拉菜单添加子菜单
            </summary>
            <param name="parentMenu">下拉菜单</param>
            <param name="index">子菜单的位置</param>
            <param name="name">子菜单的显示名称</param>
            <param name="tag">子菜单的标识字符串</param>
            <returns>返回添加的子菜单</returns>
        </member>
        <member name="M:DotNetARX.CUITools.AddSeparator(Autodesk.AutoCAD.Customization.PopMenu,System.Int32)">
            <summary>
            为菜单添加分隔条
            </summary>
            <param name="parentMenu">下拉菜单</param>
            <param name="index">分隔条的位置</param>
            <returns>返回添加的分隔条</returns>
        </member>
        <member name="M:DotNetARX.CUITools.AddToolbar(Autodesk.AutoCAD.Customization.MenuGroup,System.String)">
            <summary>
            添加工具栏
            </summary>
            <param name="menuGroup">工具栏所属的菜单组</param>
            <param name="name">工具栏的显示名称</param>
            <returns>返回添加的工具栏</returns>
        </member>
        <member name="M:DotNetARX.CUITools.AddToolbarButton(Autodesk.AutoCAD.Customization.Toolbar,System.Int32,System.String,System.String)">
            <summary>
            向工具栏添加按钮
            </summary>
            <param name="parent">按钮所属的工具栏</param>
            <param name="index">按钮在工具栏上的位置</param>
            <param name="name">按钮的显示名称</param>
            <param name="macroId">按钮的命令宏的Id</param>
            <returns>返回工具栏按钮对象</returns>
        </member>
        <member name="M:DotNetARX.CUITools.AttachToolbarToFlyout(Autodesk.AutoCAD.Customization.Toolbar,System.Int32,Autodesk.AutoCAD.Customization.Toolbar)">
            <summary>
            向工具栏添加弹出式工具栏
            </summary>
            <param name="parent">工具栏所属的父工具栏</param>
            <param name="index">弹出式工具栏在父工具栏上的位置</param>
            <param name="toolbarRef">弹出式工具栏所引用的工具栏</param>
        </member>
        <member name="T:DotNetARX.ArcTools">
            <summary>
            简化圆弧操作类
            </summary>
        </member>
        <member name="M:DotNetARX.ArcTools.CreateArcSCE(Autodesk.AutoCAD.DatabaseServices.Arc,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
            <summary>
            根据圆心、起点和终点来创建圆弧
            </summary>
            <param name="arc">圆弧对象</param>
            <param name="startPoint">起点</param>
            <param name="centerPoint">圆心</param>
            <param name="endPoint">终点</param>
        </member>
        <member name="M:DotNetARX.ArcTools.CreateArc(Autodesk.AutoCAD.DatabaseServices.Arc,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,System.Double)">
            <summary>
            根据起点、圆心和圆弧角度创建圆弧
            </summary>
            <param name="arc">圆弧对象</param>
            <param name="startPoint">起点</param>
            <param name="centerPoint">圆心</param>
            <param name="angle">圆弧角度</param>
        </member>
        <member name="M:DotNetARX.ArcTools.CreateArc(Autodesk.AutoCAD.DatabaseServices.Arc,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
            <summary>
            三点法创建圆弧
            </summary>
            <param name="arc">圆弧对象</param>
            <param name="startPoint">起点</param>
            <param name="pointOnArc">圆弧上的点</param>
            <param name="endPoint">终点</param>
        </member>
        <member name="T:DotNetARX.StackType">
            <summary>
            多行文字堆叠方式
            </summary>
        </member>
        <member name="F:DotNetARX.StackType.HorizontalFraction">
            <summary>
            水平分数(/)
            </summary>
        </member>
        <member name="F:DotNetARX.StackType.ItalicFraction">
            <summary>
            斜分数(#)
            </summary>
        </member>
        <member name="F:DotNetARX.StackType.Tolerance">
            <summary>
            公差(^)
            </summary>
        </member>
        <member name="T:DotNetARX.TextSpecialSymbol">
            <summary>
            特殊字符
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Degree">
            <summary>
            度符号(°)
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Tolerance">
            <summary>
            公差符号(±)
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Diameter">
            <summary>
            直径符号(φ)
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.AlmostEqual">
            <summary>
            几乎相等(≈)
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Angle">
            <summary>
            角度(∠)
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.LineBoundary">
            <summary>
            边界线
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.LineCenter">
            <summary>
            中心线
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Delta">
            <summary>
            增量(Δ)
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.ElectricalPhase">
            <summary>
            电相位(φ)
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.LineFlow">
            <summary>
            流线
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Identity">
            <summary>
            标识
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.InitialLength">
            <summary>
            初始长度
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.LineMonument">
            <summary>
            界碑线
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Notequal">
            <summary>
            不相等(≠)
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Ohm">
            <summary>
            欧姆
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Omega">
            <summary>
            欧米加(Ω)
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.LinePlate">
            <summary>
            地界线
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Subscript2">
            <summary>
            下标2
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Square">
            <summary>
            平方
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Cube">
            <summary>
            立方
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Overline">
            <summary>
            单行文字上划线
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Underline">
            <summary>
            单行文字下划线
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Alpha">
            <summary>
            α
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Belta">
            <summary>
            β
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.Gamma">
            <summary>
            γ 
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.SteelBar1">
            <summary>
            一级钢筋符号
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.SteelBar2">
            <summary>
            二级钢筋符号
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.SteelBar3">
            <summary>
            三级钢筋符号
            </summary>
        </member>
        <member name="F:DotNetARX.TextSpecialSymbol.SteelBar4">
            <summary>
            四级钢筋符号
            </summary>
        </member>
        <member name="T:DotNetARX.TextTools">
            <summary>
            文字操作类
            </summary>
        </member>
        <member name="M:DotNetARX.TextTools.GetText(Autodesk.AutoCAD.DatabaseServices.MText)">
            <summary>
            获取多行文字的真实内容
            </summary>
            <param name="mtext">多行文字对象</param>
            <returns>返回多行文字的真实内容</returns>
        </member>
        <member name="M:DotNetARX.TextTools.StackText(System.String,System.String,System.String,DotNetARX.StackType,System.Double)">
            <summary>
            堆叠多行文字
            </summary>
            <param name="text">堆叠分数前的文字</param>
            <param name="supText">堆叠分数的分子</param>
            <param name="subText">堆叠分数的分母</param>
            <param name="stackType">堆叠类型</param>
            <param name="scale">堆叠文字的缩放比例</param>
            <returns>返回堆叠好的文字</returns>
        </member>
        <member name="M:DotNetARX.TextTools.SetFromTextStyle(Autodesk.AutoCAD.DatabaseServices.DBText)">
            <summary>
            设置单行文本的属性为当前文字样式的属性
            </summary>
            <param name="txt">单行文本对象</param>
        </member>
        <member name="T:DotNetARX.PlotTools">
            <summary>
            打印操作类
            </summary>
        </member>
        <member name="M:DotNetARX.PlotTools.Plot(Autodesk.AutoCAD.PlottingServices.PlotEngine,Autodesk.AutoCAD.DatabaseServices.Layout,Autodesk.AutoCAD.DatabaseServices.PlotSettings,System.String,System.Int32,System.Boolean,System.Boolean,System.Boolean)">
            <summary>
            执行单一布局打印
            </summary>
            <param name="engine">打印引擎对象</param>
            <param name="layout">要打印的布局</param>
            <param name="ps">打印设置</param>
            <param name="fileName">打印文件名</param>
            <param name="copies">打印份数</param>
            <param name="isPreview">是否预览打印</param>
            <param name="showProgressDialog">是否显示打印进度框</param>
            <param name="plotToFile">是否打印到文件</param>
            <returns>返回打印状态</returns>
        </member>
        <member name="M:DotNetARX.PlotTools.MPlot(Autodesk.AutoCAD.PlottingServices.PlotEngine,System.Collections.Generic.List{Autodesk.AutoCAD.DatabaseServices.Layout},Autodesk.AutoCAD.DatabaseServices.PlotSettings,System.String,System.Int32,System.Int32,System.Boolean,System.Boolean)">
            <summary>
            执行多布局打印
            </summary>
            <param name="engine">打印引擎对象</param>
            <param name="layouts">要打印的布局列表</param>
            <param name="ps">打印设置</param>
            <param name="fileName">打印文件名</param>
            <param name="previewNum">预览的布局号，小于1表示打印</param>
            <param name="copies">打印份数</param>
            <param name="showProgressDialog">是否显示打印进度框</param>
            <param name="plotToFile">是否打印到文件</param>
            <returns>返回打印状态</returns>
        </member>
        <member name="M:DotNetARX.PlotTools.StartSheetProgress(Autodesk.AutoCAD.PlottingServices.PlotProgressDialog)">
            <summary>
            启动打印图纸进程
            </summary>
            <param name="plotDlg">打印进度框对象</param>
        </member>
        <member name="M:DotNetARX.PlotTools.EndSheetProgress(Autodesk.AutoCAD.PlottingServices.PlotProgressDialog)">
            <summary>
            终止打印图纸进程
            </summary>
            <param name="plotDlg">打印进度框对象</param>
        </member>
        <member name="M:DotNetARX.PlotTools.StartPlotProgress(Autodesk.AutoCAD.PlottingServices.PlotProgressDialog,System.Boolean)">
            <summary>
            启动打印进度框
            </summary>
            <param name="plotDlg">打印进度框对象</param>
        </member>
        <member name="M:DotNetARX.PlotTools.EndPlotProgress(Autodesk.AutoCAD.PlottingServices.PlotProgressDialog)">
            <summary>
            终止打印进度框
            </summary>
            <param name="plotDlg">打印进度框对象</param>
        </member>
        <member name="M:DotNetARX.PlotTools.DeviceMeidaToXML(System.String)">
            <summary>
            将打印设备及标准图纸尺寸清单存储到XML文件
            </summary>
            <param name="fileName">XML文件名</param>
        </member>
        <member name="M:DotNetARX.PlotTools.MeidasFromXML(System.String,System.String)">
            <summary>
            从XML文件中读取打印设备及标准图纸尺寸清单
            </summary>
            <param name="fileName">XML文件名</param>
            <returns>返回打印设备及其对应的标准图纸尺寸清单</returns>
        </member>
        <member name="M:DotNetARX.PlotTools.CopyPlotSettings(Autodesk.AutoCAD.DatabaseServices.Database,Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            从其它图形数据库中复制打印设置
            </summary>
            <param name="destdb">目的图形数据库</param>
            <param name="sourceDb">源图形数据库</param>
            <param name="plotSettingName">打印设置名称</param>
        </member>
        <member name="M:DotNetARX.PlotTools.CopyPlotSettings(Autodesk.AutoCAD.DatabaseServices.Database,Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            复制另一个图形数据库中的所有打印设置
            </summary>
            <param name="destdb">目的图形数据库</param>
            <param name="sourceDb">源图形数据库</param>
        </member>
        <member name="T:DotNetARX.GroupTools">
            <summary>
            组操作类
            </summary>
        </member>
        <member name="M:DotNetARX.GroupTools.CreateGroup(Autodesk.AutoCAD.DatabaseServices.Database,System.String,DotNetARX.ObjectIdList)">
            <summary>
            创建组
            </summary>
            <param name="db">数据库对象</param>
            <param name="groupName">组名</param>
            <param name="ids">要加入实体的ObjectId集合</param>
            <returns>返回组的Id</returns>
        </member>
        <member name="M:DotNetARX.GroupTools.AppendEntityToGroup(Autodesk.AutoCAD.DatabaseServices.ObjectId,DotNetARX.ObjectIdList)">
            <summary>
            向已有组中添加对象
            </summary>
            <param name="groupId">组对象的Id</param>
            <param name="entIds">要加入到组中的实体的ObjectId集合</param>
        </member>
        <member name="M:DotNetARX.GroupTools.GetGroups(Autodesk.AutoCAD.DatabaseServices.ObjectId)">
            <summary>
            获取实体对象所在的组
            </summary>
            <param name="entId">实体的Id</param>
            <returns>返回实体所在的组</returns>
        </member>
        <member name="M:DotNetARX.GroupTools.RemoveGroup(Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            删除组
            </summary>
            <param name="db">数据库对象</param>
            <param name="groupName">组名</param>
        </member>
        <member name="T:DotNetARX.EntTools">
            <summary>
            实体操作类
            </summary>
        </member>
        <member name="M:DotNetARX.EntTools.Move(Autodesk.AutoCAD.DatabaseServices.ObjectId,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
            <summary>
            移动实体
            </summary>
            <param name="id">实体的ObjectId</param>
            <param name="sourcePt">移动的源点</param>
            <param name="targetPt">移动的目标点</param>
        </member>
        <member name="M:DotNetARX.EntTools.Move(Autodesk.AutoCAD.DatabaseServices.Entity,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
            <summary>
            移动实体
            </summary>
            <param name="ent">实体</param>
            <param name="sourcePt">移动的源点</param>
            <param name="targetPt">移动的目标点</param>
        </member>
        <member name="M:DotNetARX.EntTools.Copy(Autodesk.AutoCAD.DatabaseServices.ObjectId,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
            <summary>
            复制实体
            </summary>
            <param name="id">实体的ObjectId</param>
            <param name="sourcePt">复制的源点</param>
            <param name="targetPt">复制的目标点</param>
            <returns>返回复制实体的ObjectId</returns>
        </member>
        <member name="M:DotNetARX.EntTools.Copy(Autodesk.AutoCAD.DatabaseServices.Entity,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
            <summary>
            复制实体
            </summary>
            <param name="ent">实体</param>
            <param name="sourcePt">复制的源点</param>
            <param name="targetPt">复制的目标点</param>
            <returns>返回复制实体的ObjectId</returns>
        </member>
        <member name="M:DotNetARX.EntTools.Rotate(Autodesk.AutoCAD.DatabaseServices.ObjectId,Autodesk.AutoCAD.Geometry.Point3d,System.Double)">
            <summary>
            旋转实体
            </summary>
            <param name="id">实体的ObjectId</param>
            <param name="basePt">旋转基点</param>
            <param name="angle">旋转角度</param>
        </member>
        <member name="M:DotNetARX.EntTools.Rotate(Autodesk.AutoCAD.DatabaseServices.Entity,Autodesk.AutoCAD.Geometry.Point3d,System.Double)">
            <summary>
            旋转实体
            </summary>
            <param name="ent">实体</param>
            <param name="basePt">旋转基点</param>
            <param name="angle">旋转角度</param>
        </member>
        <member name="M:DotNetARX.EntTools.Scale(Autodesk.AutoCAD.DatabaseServices.ObjectId,Autodesk.AutoCAD.Geometry.Point3d,System.Double)">
            <summary>
            缩放实体
            </summary>
            <param name="id">实体的ObjectId</param>
            <param name="basePt">缩放基点</param>
            <param name="scaleFactor">缩放比例</param>
        </member>
        <member name="M:DotNetARX.EntTools.Scale(Autodesk.AutoCAD.DatabaseServices.Entity,Autodesk.AutoCAD.Geometry.Point3d,System.Double)">
            <summary>
            缩放实体
            </summary>
            <param name="ent">实体</param>
            <param name="basePt">缩放基点</param>
            <param name="scaleFactor">缩放比例</param>
        </member>
        <member name="M:DotNetARX.EntTools.Mirror(Autodesk.AutoCAD.DatabaseServices.ObjectId,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,System.Boolean)">
            <summary>
            镜像实体
            </summary>
            <param name="id">实体的ObjectId</param>
            <param name="mirrorPt1">镜像轴的第一点</param>
            <param name="mirrorPt2">镜像轴的第二点</param>
            <param name="eraseSourceObject">是否删除源对象</param>
            <returns>返回镜像实体的ObjectId</returns>
        </member>
        <member name="M:DotNetARX.EntTools.Mirror(Autodesk.AutoCAD.DatabaseServices.Entity,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,System.Boolean)">
            <summary>
            镜像实体
            </summary>
            <param name="ent">实体</param>
            <param name="mirrorPt1">镜像轴的第一点</param>
            <param name="mirrorPt2">镜像轴的第二点</param>
            <param name="eraseSourceObject">是否删除源对象</param>
            <returns>返回镜像实体的ObjectId</returns>
        </member>
        <member name="M:DotNetARX.EntTools.Offset(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.Double)">
            <summary>
            偏移实体
            </summary>
            <param name="id">实体的ObjectId</param>
            <param name="dis">偏移距离</param>
            <returns>返回偏移后的实体Id集合</returns>
        </member>
        <member name="M:DotNetARX.EntTools.Offset(Autodesk.AutoCAD.DatabaseServices.Entity,System.Double)">
            <summary>
            偏移实体
            </summary>
            <param name="ent">实体</param>
            <param name="dis">偏移距离</param>
            <returns>返回偏移后的实体集合</returns>
        </member>
        <member name="M:DotNetARX.EntTools.ArrayRectang(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.Int32,System.Int32,System.Double,System.Double)">
            <summary>
            矩形阵列实体
            </summary>
            <param name="id">实体的ObjectId</param>
            <param name="numRows">矩形阵列的行数,该值必须为正数</param>
            <param name="numCols">矩形阵列的列数,该值必须为正数</param>
            <param name="disRows">行间的距离</param>
            <param name="disCols">列间的距离</param>
            <returns>返回阵列后的实体集合的ObjectId</returns>
        </member>
        <member name="M:DotNetARX.EntTools.ArrayPolar(Autodesk.AutoCAD.DatabaseServices.ObjectId,Autodesk.AutoCAD.Geometry.Point3d,System.Int32,System.Double)">
            <summary>
            环形阵列实体
            </summary>
            <param name="id">实体的ObjectId</param>
            <param name="cenPt">环形阵列的中心点</param>
            <param name="numObj">在环形阵列中所要创建的对象数量</param>
            <param name="angle">以弧度表示的填充角度，正值表示逆时针方向旋转，负值表示顺时针方向旋转，如果角度为0则出错</param>
            <returns>返回阵列后的实体集合的ObjectId</returns>
        </member>
        <member name="M:DotNetARX.EntTools.Erase(Autodesk.AutoCAD.DatabaseServices.ObjectId)">
            <summary>
            删除实体
            </summary>
            <param name="id">实体的ObjectId</param>
        </member>
        <member name="T:DotNetARX.XDataTools">
            <summary>
            扩展数据操作类
            </summary>
        </member>
        <member name="M:DotNetARX.XDataTools.AddXData(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String,DotNetARX.TypedValueList)">
            <summary>
            为对象添加扩展数据
            </summary>
            <param name="id">对象的Id</param>
            <param name="regAppName">注册应用程序名</param>
            <param name="values">要添加的扩展数据项列表</param>
        </member>
        <member name="M:DotNetARX.XDataTools.GetXData(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String)">
            <summary>
            获取对象的扩展数据
            </summary>
            <param name="id">对象的Id</param>
            <param name="regAppName">注册应用程序名</param>
            <returns>返回获得的扩展数据</returns>
        </member>
        <member name="M:DotNetARX.XDataTools.ModXData(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String,Autodesk.AutoCAD.DatabaseServices.DxfCode,System.Object,System.Object)">
            <summary>
            修改扩展数据
            </summary>
            <param name="id">对象的Id</param>
            <param name="regAppName">注册应用程序名</param>
            <param name="code">扩展数据的类型</param>
            <param name="oldValue">原来的扩展数据值</param>
            <param name="newValue">新的扩展数据值</param>
        </member>
        <member name="M:DotNetARX.XDataTools.RemoveXData(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String)">
            <summary>
            删除指定注册应用程序下的扩展数据
            </summary>
            <param name="id">对象的Id</param>
            <param name="regAppName">注册应用程序名</param>
        </member>
        <member name="T:DotNetARX.RegionTools">
            <summary>
            面域操作类
            </summary>
        </member>
        <member name="M:DotNetARX.RegionTools.GetCentroid(Autodesk.AutoCAD.DatabaseServices.Region)">
            <summary>
            获取面域的质心
            </summary>
            <param name="region">面域对象</param>
            <returns>返回质心的坐标</returns>
        </member>
        <member name="M:DotNetARX.RegionTools.GetMomInertia(Autodesk.AutoCAD.DatabaseServices.Region)">
            <summary>
            获取面域的惯性矩
            </summary>
            <param name="region">面域对象</param>
            <returns>返回惯性矩</returns>
        </member>
        <member name="M:DotNetARX.RegionTools.GetProdInertia(Autodesk.AutoCAD.DatabaseServices.Region)">
            <summary>
            获取面域的惯性积
            </summary>
            <param name="region">面域对象</param>
            <returns>返回惯性积</returns>
        </member>
        <member name="M:DotNetARX.RegionTools.GetPrinMoments(Autodesk.AutoCAD.DatabaseServices.Region)">
            <summary>
            获取面域的主力矩
            </summary>
            <param name="region">面域对象</param>
            <returns>返回主力矩</returns>
        </member>
        <member name="M:DotNetARX.RegionTools.GetPrinAxes(Autodesk.AutoCAD.DatabaseServices.Region)">
            <summary>
            获取面域的主方向
            </summary>
            <param name="region">面域对象</param>
            <returns>返回主方向</returns>
        </member>
        <member name="M:DotNetARX.RegionTools.GetRadiiGyration(Autodesk.AutoCAD.DatabaseServices.Region)">
            <summary>
            获取面域的旋转半径
            </summary>
            <param name="region">面域对象</param>
            <returns>返回旋转半径</returns>
        </member>
        <member name="M:DotNetARX.RegionTools.GetExtentsLow(Autodesk.AutoCAD.DatabaseServices.Region)">
            <summary>
            获取面域边界框的下限
            </summary>
            <param name="region">面域对象</param>
            <returns>返回边界框的下限</returns>
        </member>
        <member name="M:DotNetARX.RegionTools.GetExtentsHigh(Autodesk.AutoCAD.DatabaseServices.Region)">
            <summary>
            获取面域边界框的上限
            </summary>
            <param name="region">面域对象</param>
            <returns>返回边界框的上限</returns>
        </member>
        <member name="M:DotNetARX.RegionTools.CreateRegion(Autodesk.AutoCAD.DatabaseServices.Curve[])">
            <summary>
            根据曲线创建面域
            </summary>
            <param name="curves">曲线</param>
            <returns>返回创建的面域列表</returns>
        </member>
        <member name="M:DotNetARX.LinqToCAD.GetEntsInDatabase``1(Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            获取数据库中类型为T的所有实体(对象打开为读）
            </summary>
            <typeparam name="T">实体的类型</typeparam>
            <param name="db">数据库对象</param>
            <returns>返回数据库中类型为T的实体</returns>
        </member>
        <member name="M:DotNetARX.LinqToCAD.GetEntsInDatabase``1(Autodesk.AutoCAD.DatabaseServices.Database,Autodesk.AutoCAD.DatabaseServices.OpenMode,System.Boolean)">
            <summary>
             获取数据库中类型为T的所有实体
            </summary>
            <typeparam name="T">实体的类型</typeparam>
            <param name="db">数据库对象</param>
            <param name="mode">实体打开方式</param>
            <param name="openErased">是否打开已删除的实体</param>
            <returns>返回数据库中类型为T的实体</returns>
        </member>
        <member name="M:DotNetARX.LinqToCAD.GetEntsInModelSpace``1(Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            获取模型空间中类型为T的所有实体(对象打开为读）
            </summary>
            <typeparam name="T">实体的类型</typeparam>
            <param name="db">数据库对象</param>
            <returns>返回模型空间中类型为T的实体</returns>
        </member>
        <member name="M:DotNetARX.LinqToCAD.GetEntsInModelSpace``1(Autodesk.AutoCAD.DatabaseServices.Database,Autodesk.AutoCAD.DatabaseServices.OpenMode,System.Boolean)">
            <summary>
            获取模型空间中类型为T的所有实体
            </summary>
            <typeparam name="T">实体的类型</typeparam>
            <param name="db">数据库对象</param>
            <param name="mode">实体打开方式</param>
            <param name="openErased">是否打开已删除的实体</param>
            <returns>返回模型空间中类型为T的实体</returns>
        </member>
        <member name="T:DotNetARX.DictTools">
            <summary>
            字典操作类，包括扩展字典与有名对象字典
            </summary>
        </member>
        <member name="M:DotNetARX.DictTools.AddXrecord(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String,DotNetARX.TypedValueList)">
            <summary>
            添加扩展记录
            </summary>
            <param name="id">对象的Id</param>
            <param name="searchKey">扩展记录名称</param>
            <param name="values">扩展记录的内容</param>
            <returns>返回添加的扩展记录的Id</returns>
        </member>
        <member name="M:DotNetARX.DictTools.GetXrecord(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String)">
            <summary>
            获取扩展记录
            </summary>
            <param name="id">对象的Id</param>
            <param name="searchKey">扩展记录名称</param>
            <returns>返回扩展记录的内容</returns>
        </member>
        <member name="M:DotNetARX.DictTools.AddNamedDictionary(Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            添加有名对象字典项
            </summary>
            <param name="db">数据库</param>
            <param name="searchKey">有名对象字典项的名称</param>
            <returns>返回添加的有名对象字典项的Id</returns>
        </member>
        <member name="T:DotNetARX.XrefTools">
            <summary>
            外部参照操作类
            </summary>
        </member>
        <member name="M:DotNetARX.XrefTools.AttachXref(Autodesk.AutoCAD.DatabaseServices.Database,System.String,System.String,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Scale3d,System.Double,System.Boolean)">
            <summary>
            将外部参照插入到图形
            </summary>
            <param name="db">数据库对象</param>
            <param name="fileName">包含完整路径的外部参照文件名</param>
            <param name="blockName">参照名</param>
            <param name="insertionPoint">外部参照块的插入点</param>
            <param name="scaleFactors">外部参照块的缩放因子</param>
            <param name="rotation">外部参照块的旋转角度，以弧度表示</param>
            <param name="isOverlay">外部参照块的类型，为true时表示覆盖，为false时表示附着</param>
            <returns></returns>
        </member>
        <member name="M:DotNetARX.ViewportTools.CurrentViewportTableRecordId(Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            获取当前活动视口
            </summary>
            <param name="db">数据库对象</param>
            <returns>返回当前活动视口的Id</returns>
        </member>
        <member name="T:DotNetARX.HatchGradientName">
            <summary>
            渐变色填充的图案名称
            </summary>
        </member>
        <member name="F:DotNetARX.HatchGradientName.Linear">
            <summary>
            线状渐变
            </summary>
        </member>
        <member name="F:DotNetARX.HatchGradientName.Cylinder">
            <summary>
            圆柱状渐变
            </summary>
        </member>
        <member name="F:DotNetARX.HatchGradientName.Invcylinder">
            <summary>
            反圆柱状渐变
            </summary>
        </member>
        <member name="F:DotNetARX.HatchGradientName.Spherical">
            <summary>
            球状渐变
            </summary>
        </member>
        <member name="F:DotNetARX.HatchGradientName.Invspherical">
            <summary>
            反球状渐变
            </summary>
        </member>
        <member name="F:DotNetARX.HatchGradientName.Hemisperical">
            <summary>
            半球状渐变
            </summary>
        </member>
        <member name="F:DotNetARX.HatchGradientName.InvHemisperical">
            <summary>
            反半球状渐变
            </summary>
        </member>
        <member name="F:DotNetARX.HatchGradientName.Curved">
            <summary>
            抛物面状渐变
            </summary>
        </member>
        <member name="F:DotNetARX.HatchGradientName.Incurved">
            <summary>
            反抛物面状渐变
            </summary>
        </member>
        <member name="T:DotNetARX.HatchPalletteDialog">
            <summary>
            填充图案选项板类
            </summary>
        </member>
        <member name="M:DotNetARX.HatchPalletteDialog.GetPattern">
            <summary>
            获取用户选择的填充图案名称
            </summary>
            <returns>返回填充图案名称</returns>
        </member>
        <member name="M:DotNetARX.HatchPalletteDialog.#ctor">
            <summary>
            构造函数，在填充图案选项板中显示自定义标签
            </summary>
        </member>
        <member name="M:DotNetARX.HatchPalletteDialog.ShowDialog">
            <summary>
            显示填充图案选项板
            </summary>
            <returns>如果用户选择了填充图案，则返回true，否则返回false</returns>
        </member>
        <member name="P:DotNetARX.HatchPalletteDialog.ShowCustom">
            <summary>
            是否显示自定义标签
            </summary>
        </member>
        <member name="T:DotNetARX.HatchTools">
            <summary>
            填充操作类
            </summary>
        </member>
        <member name="M:DotNetARX.HatchTools.CreateHatch(Autodesk.AutoCAD.DatabaseServices.Hatch,Autodesk.AutoCAD.DatabaseServices.HatchPatternType,System.String,System.Boolean)">
            <summary>
            创建图案填充
            </summary>
            <param name="hatch">填充对象</param>
            <param name="patternType">填充图案类型</param>
            <param name="patternName">填充图案名</param>
            <param name="associative">填充是否与边界关联</param>
        </member>
        <member name="M:DotNetARX.HatchTools.CreateGradientHatch(Autodesk.AutoCAD.DatabaseServices.Hatch,DotNetARX.HatchGradientName,Autodesk.AutoCAD.Colors.Color,Autodesk.AutoCAD.Colors.Color,System.Boolean)">
            <summary>
            创建渐变色填充
            </summary>
            <param name="hatch">填充对象</param>
            <param name="gradientName">渐变色填充的图案名称</param>
            <param name="color1">渐变色填充的起始颜色</param>
            <param name="color2">渐变色填充的结束颜色</param>
            <param name="associative">填充是否与边界关联</param>
        </member>
        <member name="P:DotNetARX.HatchTools.CurrentPattern">
            <summary>
            设置或读取默认填充图案，其名称最多可包含 34 个字符，其中不能有空格。
            </summary>
        </member>
        <member name="T:DotNetARX.DimStyleTools">
            <summary>
            标注样式操作类
            </summary>
        </member>
        <member name="M:DotNetARX.DimStyleTools.AddDimStyle(Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            创建一个新的标注样式
            </summary>
            <param name="db">数据库对象</param>
            <param name="styleName">标注样式名</param>
            <returns>返回新建的标注样式的Id</returns>
        </member>
        <member name="T:DotNetARX.EllipseTools">
            <summary>
            椭圆操作类
            </summary>
        </member>
        <member name="M:DotNetARX.EllipseTools.CreateEllipse(Autodesk.AutoCAD.DatabaseServices.Ellipse,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d)">
            <summary>
            根据外接矩形创建椭圆
            </summary>
            <param name="ellipse">椭圆对象</param>
            <param name="pt1">外接矩形的角点</param>
            <param name="pt2">外接矩形的角点</param>
        </member>
        <member name="T:DotNetARX.DimFormatCode">
            <summary>
            与公差标注有关的特殊格式代码
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.Angular">
            <summary>
            倾斜度（∠）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.VerticalLine">
            <summary>
            垂直度（⊥）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.Flatness">
            <summary>
            平面度（◇）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.HalfCircleClosed">
            <summary>
            面轮廓度（封闭的半圆）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.SingleCircle">
            <summary>
            圆度（○）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.Parallel">
            <summary>
            平行度（∥）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.Cylindricity">
            <summary>
            圆柱度
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.CircularRunout">
            <summary>
            圆跳动度（↗）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.SymmetrySymbol">
            <summary>
            对称度
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.Position">
            <summary>
            位置度（⊕）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.HalfCircle">
            <summary>
            线轮廓度（⌒）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.CircleL">
            <summary>
            最小实体要求（带圆圈的L）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.CircleM">
            <summary>
            最大实体要求（带圆圈的M）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.Diameter">
            <summary>
            公差直径（φ）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.Square">
            <summary>
            正方形（□）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.CircleP">
            <summary>
            延伸公差带（带圆圈的P）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.CenterLine">
            <summary>
            中心线（C和L重叠）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.TwoCircles">
            <summary>
            同轴度（◎）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.CircleS">
            <summary>
            不考虑特征尺寸（带圆圈的S）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.TotalRunout">
            <summary>
            全跳动度（符号为两带箭头的斜线）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.Line">
            <summary>
            直线度（―）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.CounterBore">
            <summary>
            机械制图中的柱形沉孔和锪平面孔
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.CounterSink">
            <summary>
            机械制图中的埋头孔（∨）
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.Depth">
            <summary>
            机械制图中的沉孔深度
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.ConicalTaper">
            <summary>
            锥形接续器符号
            </summary>
        </member>
        <member name="F:DotNetARX.DimFormatCode.Slope">
            <summary>
            机械制图中的锥度（⊿）
            </summary>
        </member>
        <member name="T:DotNetARX.DimArrowBlock">
            <summary>
            标注中的箭头符号
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.ClosedFilled">
            <summary>
            实心闭合
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.Dot">
            <summary>
            点
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.DotSmall">
            <summary>
            小点
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.DotBlank">
            <summary>
            空心点
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.Origin">
            <summary>
            原点标记
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.Origin2">
            <summary>
            原点标记2
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.Open">
            <summary>
            打开
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.RightAngle">
            <summary>
            直角
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.Angle30">
            <summary>
            30度角
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.Closed">
            <summary>
            闭合
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.DotSmallBlank">
            <summary>
            空心小点
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.None">
            <summary>
            无
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.Oblique">
            <summary>
            倾斜
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.BoxFilled">
            <summary>
            实心框
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.Box">
            <summary>
            框
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.ClosedBlank">
            <summary>
            空心闭合
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.TriangleFilled">
            <summary>
            实心基准三角形
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.Triangle">
            <summary>
            基准三角形
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.Integral">
            <summary>
            积分
            </summary>
        </member>
        <member name="F:DotNetARX.DimArrowBlock.ArchitecturalTick">
            <summary>
            建筑标记
            </summary>
        </member>
        <member name="T:DotNetARX.LeaderBlockContent">
            <summary>
            AutoCAD自带的用于多重引线注释块的名称
            </summary>
        </member>
        <member name="F:DotNetARX.LeaderBlockContent.Detail">
            <summary>
            详细信息标注
            </summary>
        </member>
        <member name="F:DotNetARX.LeaderBlockContent.Box">
            <summary>
            方框（□）
            </summary>
        </member>
        <member name="F:DotNetARX.LeaderBlockContent.Circle">
            <summary>
            圆（○）
            </summary>
        </member>
        <member name="F:DotNetARX.LeaderBlockContent.Hexagon">
            <summary>
            正六边形
            </summary>
        </member>
        <member name="F:DotNetARX.LeaderBlockContent.Slot">
            <summary>
            槽
            </summary>
        </member>
        <member name="F:DotNetARX.LeaderBlockContent.Triangle">
            <summary>
            三角形（△）
            </summary>
        </member>
        <member name="T:DotNetARX.DimTools">
            <summary>
            标注操作类（含引线、形位公差）
            </summary>
        </member>
        <member name="M:DotNetARX.DimTools.GetArrowObjectId(Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            获取与名称对应的箭头块的ObjectId
            </summary>
            <param name="db">数据库对象</param>
            <param name="arrowName">箭头名</param>
            <returns>返回指定箭头块的ObjectId</returns>
        </member>
        <member name="M:DotNetARX.DimTools.CreateTolerance(Autodesk.AutoCAD.DatabaseServices.FeatureControlFrame,System.String,System.String,System.String,System.String,System.String)">
            <summary>
            设置形位公差值
            </summary>
            <param name="frame">形位公差特征控制框对象</param>
            <param name="geometricSym">几何特征符号，表示公差的几何特征，例如位置、轮廓、形状、方向或跳动</param>
            <param name="torlerance">公差值</param>
            <param name="firstDatum">第一级基准要素</param>
            <param name="secondDatum">第二级基准要素</param>
            <param name="thirdDatum">第三级基准要素</param>
        </member>
        <member name="P:DotNetARX.DimTools.ArrowBlock">
            <summary>
            当前尺寸线箭头符号
            </summary>
        </member>
        <member name="T:DotNetARX.TableTools">
            <summary>
            表格操作类
            </summary>
        </member>
        <member name="P:DotNetARX.TableTools.AllRows">
            <summary>
            所有行的标志位（包括标题行、数据行）
            </summary>
        </member>
        <member name="T:DotNetARX.DynBlockPropTypeCode">
            <summary>
            动态块的动态属性类型
            </summary>
        </member>
        <member name="F:DotNetARX.DynBlockPropTypeCode.String">
            <summary>
            字符串
            </summary>
        </member>
        <member name="F:DotNetARX.DynBlockPropTypeCode.Real">
            <summary>
            实数
            </summary>
        </member>
        <member name="F:DotNetARX.DynBlockPropTypeCode.Short">
            <summary>
            短整型
            </summary>
        </member>
        <member name="F:DotNetARX.DynBlockPropTypeCode.Long">
            <summary>
            长整型
            </summary>
        </member>
        <member name="T:DotNetARX.BlockTools">
            <summary>
            块操作类
            </summary>
        </member>
        <member name="M:DotNetARX.BlockTools.AddBlockTableRecord(Autodesk.AutoCAD.DatabaseServices.Database,System.String,System.Collections.Generic.List{Autodesk.AutoCAD.DatabaseServices.Entity})">
            <summary>
            创建一个块表记录并添加到数据库中
            </summary>
            <param name="db">数据库对象</param>
            <param name="blockName">块名</param>
            <param name="ents">加入块中的实体列表</param>
            <returns>返回块表记录的Id</returns>
        </member>
        <member name="M:DotNetARX.BlockTools.AddBlockTableRecord(Autodesk.AutoCAD.DatabaseServices.Database,System.String,Autodesk.AutoCAD.DatabaseServices.Entity[])">
            <summary>
            创建一个块表记录并添加到数据库中
            </summary>
            <param name="db">数据库对象</param>
            <param name="blockName">块名</param>
            <param name="ents">加入块中的实体列表</param>
            <returns>返回块表记录的Id</returns>
        </member>
        <member name="M:DotNetARX.BlockTools.InsertBlockReference(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String,System.String,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Scale3d,System.Double)">
            <summary>
            在AutoCAD图形中插入块参照
            </summary>
            <param name="spaceId">块参照要加入的模型空间或图纸空间的Id</param>
            <param name="layer">块参照要加入的图层名</param>
            <param name="blockName">块参照所属的块名</param>
            <param name="position">插入点</param>
            <param name="scale">缩放比例</param>
            <param name="rotateAngle">旋转角度</param>
            <returns>返回块参照的Id</returns>
        </member>
        <member name="M:DotNetARX.BlockTools.InsertBlockReference(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String,System.String,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Scale3d,System.Double,System.Collections.Generic.Dictionary{System.String,System.String})">
            <summary>
            在AutoCAD图形中插入块参照
            </summary>
            <param name="spaceId">块参照要加入的模型空间或图纸空间的Id</param>
            <param name="layer">块参照要加入的图层名</param>
            <param name="blockName">块参照所属的块名</param>
            <param name="position">插入点</param>
            <param name="scale">缩放比例</param>
            <param name="rotateAngle">旋转角度</param>
            <param name="attNameValues">属性的名称与取值</param>
            <returns>返回块参照的Id</returns>
        </member>
        <member name="M:DotNetARX.BlockTools.UpdateAttributesInBlock(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.Collections.Generic.Dictionary{System.String,System.String})">
            <summary>
            更新块参照中的属性值
            </summary>
            <param name="blockRefId">块参照的Id</param>
            <param name="attNameValues">需要更新的属性名称与取值</param>
        </member>
        <member name="M:DotNetARX.BlockTools.GetBlockName(Autodesk.AutoCAD.DatabaseServices.ObjectId)">
            <summary>
            获取块参照的块名（包括动态块）
            </summary>
            <param name="id">块参照的Id</param>
            <returns>返回块名</returns>
        </member>
        <member name="M:DotNetARX.BlockTools.GetBlockName(Autodesk.AutoCAD.DatabaseServices.BlockReference)">
            <summary>
            获取块参照的块名（包括动态块）
            </summary>
            <param name="bref">块参照</param>
            <returns>返回块名</returns>
        </member>
        <member name="M:DotNetARX.BlockTools.AddAttsToBlock(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.Collections.Generic.List{Autodesk.AutoCAD.DatabaseServices.AttributeDefinition})">
            <summary>
            为块表记录添加属性
            </summary>
            <param name="blockId">块表记录的Id</param>
            <param name="atts">要加入的块属性列表</param>
        </member>
        <member name="M:DotNetARX.BlockTools.AddAttsToBlock(Autodesk.AutoCAD.DatabaseServices.ObjectId,Autodesk.AutoCAD.DatabaseServices.AttributeDefinition[])">
            <summary>
            为块表记录添加属性
            </summary>
            <param name="blockId">块表记录的Id</param>
            <param name="atts">要加入的块属性列表</param>
        </member>
        <member name="M:DotNetARX.BlockTools.GetDynBlockValue(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String)">
            <summary>
            获取动态块的动态属性值
            </summary>
            <param name="blockId">动态块的Id</param>
            <param name="propName">需要查找的动态属性名</param>
            <returns>返回指定动态属性的值</returns>
        </member>
        <member name="M:DotNetARX.BlockTools.GetDynProperties(Autodesk.AutoCAD.DatabaseServices.ObjectId)">
            <summary>
            获得动态块的所有动态属性
            </summary>
            <param name="blockId">动态块的Id</param>
            <returns>返回动态块的所有属性</returns>
        </member>
        <member name="M:DotNetARX.BlockTools.SetDynBlockValue(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String,System.Object)">
            <summary>
            设置动态块的动态属性
            </summary>
            <param name="blockId">动态块的ObjectId</param>
            <param name="propName">动态属性的名称</param>
            <param name="value">动态属性的值</param>
        </member>
        <member name="M:DotNetARX.ViewTableTools.Wcs2Dcs(Autodesk.AutoCAD.DatabaseServices.AbstractViewTableRecord)">
            <summary>
            获取WCS到DCS的转换矩阵
            </summary>
            <param name="vtr">视图（ViewTableRecord）或视口（ViewportTableRecord）</param>
            <returns></returns>
        </member>
        <member name="M:DotNetARX.ViewTableTools.Zoom(Autodesk.AutoCAD.EditorInput.Editor,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,System.Double)">
            <summary>
            视图缩放
            </summary>
            <param name="ed">命令行对象</param>
            <param name="ptMin">要显示区域的左下角点</param>
            <param name="ptMax">要显示区域的右上角点</param>
            <param name="ptCenter">要显示区域的中心点</param>
            <param name="factor">缩放比例</param>
        </member>
        <member name="T:DotNetARX.PolylineTools">
            <summary>
            多段线操作类
            </summary>
        </member>
        <member name="M:DotNetARX.PolylineTools.CreatePolyline(Autodesk.AutoCAD.DatabaseServices.Polyline,Autodesk.AutoCAD.Geometry.Point3dCollection)">
            <summary>
            通过三维点集合创建多段线
            </summary>
            <param name="pline">多段线对象</param>
            <param name="pts">多段线的顶点</param>
        </member>
        <member name="M:DotNetARX.PolylineTools.CreatePolyline(Autodesk.AutoCAD.DatabaseServices.Polyline,Autodesk.AutoCAD.Geometry.Point2dCollection)">
            <summary>
            通过二维点集合创建多段线
            </summary>
            <param name="pline">多段线对象</param>
            <param name="pts">多段线的顶点</param>
        </member>
        <member name="M:DotNetARX.PolylineTools.CreatePolyline(Autodesk.AutoCAD.DatabaseServices.Polyline,Autodesk.AutoCAD.Geometry.Point2d[])">
            <summary>
            通过不固定的点创建多段线
            </summary>
            <param name="pline">多段线对象</param>
            <param name="pts">多段线的顶点</param>
        </member>
        <member name="M:DotNetARX.PolylineTools.CreateRectangle(Autodesk.AutoCAD.DatabaseServices.Polyline,Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d)">
            <summary>
            创建矩形
            </summary>
            <param name="pline">多段线对象</param>
            <param name="pt1">矩形的角点</param>
            <param name="pt2">矩形的角点</param>
        </member>
        <member name="M:DotNetARX.PolylineTools.CreatePolygon(Autodesk.AutoCAD.DatabaseServices.Polyline,Autodesk.AutoCAD.Geometry.Point2d,System.Int32,System.Double)">
            <summary>
            创建多边形
            </summary>
            <param name="pline">多段线对象</param>
            <param name="centerPoint">多边形中心点</param>
            <param name="number">边数</param>
            <param name="radius">外接圆半径</param>
        </member>
        <member name="M:DotNetARX.PolylineTools.CreatePolyCircle(Autodesk.AutoCAD.DatabaseServices.Polyline,Autodesk.AutoCAD.Geometry.Point2d,System.Double)">
            <summary>
            创建多段线形式的圆
            </summary>
            <param name="pline">多段线对象</param>
            <param name="centerPoint">圆心</param>
            <param name="radius">半径</param>
        </member>
        <member name="M:DotNetARX.PolylineTools.CreatePolyArc(Autodesk.AutoCAD.DatabaseServices.Polyline,Autodesk.AutoCAD.Geometry.Point2d,System.Double,System.Double,System.Double)">
            <summary>
            创建多段线形式的圆弧
            </summary>
            <param name="pline">多段线对象</param>
            <param name="centerPoint">圆弧的圆心</param>
            <param name="radius">圆弧的半径</param>
            <param name="startAngle">起始角度</param>
            <param name="endAngle">终止角度</param>
        </member>
        <member name="T:DotNetARX.MLineTools">
            <summary>
            多线样式操作类
            </summary>
        </member>
        <member name="M:DotNetARX.MLineTools.CreateMLineStyle(Autodesk.AutoCAD.DatabaseServices.Database,System.String,System.Collections.Generic.List{Autodesk.AutoCAD.DatabaseServices.MlineStyleElement})">
            <summary>
            创建一个新的多线样式
            </summary>
            <param name="db">数据库对象</param>
            <param name="styleName">多线样式名</param>
            <param name="elements">加入到多线样式的元素集合</param>
            <returns>返回加入的多线样式的Id</returns>
        </member>
        <member name="M:DotNetARX.MLineTools.RemoveMLineStyle(Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            删除多线样式
            </summary>
            <param name="db">数据库对象</param>
            <param name="styleName">多线样式名</param>
        </member>
        <member name="T:DotNetARX.DocumentTools">
            <summary>
            文档操作类
            </summary>
        </member>
        <member name="M:DotNetARX.DocumentTools.Saved(Autodesk.AutoCAD.ApplicationServices.Document)">
            <summary>
            确定文档中是否有未保存的修改。
            </summary>
            <param name="doc">文档对象</param>
            <returns>如果有未保存的修改，则返回true，否则返回false。</returns>
        </member>
        <member name="M:DotNetARX.DocumentTools.Save(Autodesk.AutoCAD.ApplicationServices.Document)">
            <summary>
            保存已有文档
            </summary>
            <param name="doc">文档对象</param>
        </member>
        <member name="T:DotNetARX.LayerTools">
            <summary>
            图层操作类
            </summary>
        </member>
        <member name="M:DotNetARX.LayerTools.AddLayer(Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            创建新图层
            </summary>
            <param name="db">数据库对象</param>
            <param name="layerName">图层名</param>
            <returns>返回新建图层的ObjectId</returns>
        </member>
        <member name="M:DotNetARX.LayerTools.SetLayerColor(Autodesk.AutoCAD.DatabaseServices.Database,System.String,System.Int16)">
            <summary>
            设置图层的颜色
            </summary>
            <param name="db">数据库对象</param>
            <param name="layerName">图层名</param>
            <param name="colorIndex">颜色索引</param>
            <returns>如果成功设置图层颜色，则返回true，否则返回false</returns>
        </member>
        <member name="M:DotNetARX.LayerTools.SetCurrentLayer(Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            将指定的图层设置为当前层
            </summary>
            <param name="db">数据库对象</param>
            <param name="layerName">图层名</param>
            <returns>如果设置成功，则返回ture</returns>
        </member>
        <member name="M:DotNetARX.LayerTools.GetAllLayers(Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            获取当前图形中所有的图层
            </summary>
            <param name="db">数据库对象</param>
            <returns>返回所有的层表记录</returns>
        </member>
        <member name="M:DotNetARX.LayerTools.DeleteLayer(Autodesk.AutoCAD.DatabaseServices.Database,System.String)">
            <summary>
            删除指定名称的图层
            </summary>
            <param name="db">数据库对象</param>
            <param name="layerName">图层名</param>
            <returns>如果删除成功，则返回true，否则返回false</returns>
        </member>
        <member name="M:DotNetARX.LayerTools.GetAllLayerObjectIds(Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            获取所有图层的ObjectId
            </summary>
            <param name="db">数据库对象</param>
            <returns>返回所有图层的ObjectId</returns>
        </member>
    </members>
</doc>
